#!/bin/bash

FILE="instances/NL12.txt"
PENALIZATION_VALUE=10000
CORES=1

ELITE=0.5
SURVIVOR=0.75
MAX_GEN=500
N_POP=1000
TIMEOUT_LS=5000000
LOCAL_SEARCH=true
PENALIZATION=true
NUM_RUNS=30
SEED=2026
LS_PROBABILITY=0.1

(cd ttp && ./bin/ttp_opt "$FILE" "$PENALIZATION_VALUE" "$CORES" "$ELITE" "$SURVIVOR" "$MAX_GEN" "$N_POP" "$TIMEOUT_LS" "$LOCAL_SEARCH" "$PENALIZATION" "$NUM_RUNS" "$SEED" "$LS_PROBABILITY")